[features]
seeds = false 
skip-lint = false

[programs.localnet]
solana_anchor_sveltekit_multiple_programs = "B29aHXp7o9Aa4PUwHsNxYREXP5vzw4KmAJbivfntTZ6X"
nfts_mint_sell = "BxkVzPHMxjtPqwipVHqmUyw1Ftr33Vd8FFxcRByDHMgJ"
onchain_voting = "7SxznnN7ztjk4W9xx5FP7GbjkydxUPzXzFthoMvLMdSs"
onchain_voting_multiple_polls = "2abHAR3JLTTtm1M8SsuWCriuJBmSXvSApMyszuVKTDJo"
pdas_instruction_data = "FsQ7Br8rjcPMmL9BCQnDwnvVEYqYWoiF4gAX6HZ69S2L"
non_custodial_escrow = "2StMWoVSWWjefwhoFsvjXVcaFABDBeMaFH2pKarQGjdW"
program_1 = "4wF9FmzBGs1oCYPMfdCXEbrhajWHdCQePjqAgqX52HUJ"
program_2 = "3i5S58AWdLzpSbXaiEQp1pQvZBH4ybCdCeCNpDcgeFaf"
program_3 = "E9zwFX6bW5HdxtrpjoAYrNNmLSK48HaJ7g1HDeu51hvf"

[programs.devnet]
solana_anchor_sveltekit_multiple_programs = "B29aHXp7o9Aa4PUwHsNxYREXP5vzw4KmAJbivfntTZ6X"
nfts_mint_sell = "BxkVzPHMxjtPqwipVHqmUyw1Ftr33Vd8FFxcRByDHMgJ"
onchain_voting = "7SxznnN7ztjk4W9xx5FP7GbjkydxUPzXzFthoMvLMdSs"
onchain_voting_multiple_polls = "2abHAR3JLTTtm1M8SsuWCriuJBmSXvSApMyszuVKTDJo"
pdas_instruction_data = "FsQ7Br8rjcPMmL9BCQnDwnvVEYqYWoiF4gAX6HZ69S2L"
non_custodial_escrow = "2StMWoVSWWjefwhoFsvjXVcaFABDBeMaFH2pKarQGjdW"
program_1 = "4wF9FmzBGs1oCYPMfdCXEbrhajWHdCQePjqAgqX52HUJ"
program_2 = "3i5S58AWdLzpSbXaiEQp1pQvZBH4ybCdCeCNpDcgeFaf"
program_3 = "E9zwFX6bW5HdxtrpjoAYrNNmLSK48HaJ7g1HDeu51hvf"

[workspace]
types = "app/src/idl/"  # Will copy IDL to frontend app as TS (not JSON!)

# [registry]
# url = "https://api.apr.dev"
[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "http://localhost:8899" #"localnet" #"devnet"
wallet = "/Users/gaylonalfano/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-escrow = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/non-custodial-escrow.ts"
test-polls = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/onchain-voting-multiple-polls.ts"
